eureka:
  client:
    register-with-eureka: false

server:
  port: 8080

spring:
  application:
    name: gateway-msvc
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-msvc
          uri: lb://product-msvc
          predicates:
            - Path=/products/**
        - id: item-msvc
          uri: lb://item-msvc
          predicates:
            - Path=/items/**

