eureka:
  client:
    register-with-eureka: false

server:
  port: 8080

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  zipkin:
    base_url: http://localhost:9411
  application:
    name: gateway-msvc
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:

        - id: product-msvc
          uri: lb://product-msvc
          predicates:
            - Path=/products/**
          filters:
            - name: CircuitBreaker
              args:
                name: products
                statusCodes: 500
                fallbackUri: forward:/items/3/quantity/1
            # - StripPrefix=2
            - SesameStreet=The Cookie Monster is Here,user,CookieMonster # shortcutFieldOrder() name()



        - id: item-msvc
          uri: lb://item-msvc
          predicates:
            - Path=/items/**
          filters:
            - AddRequestHeader=token-request, 8761
            - AddResponseHeader=token-response, 1678
            - SetResponseHeader=Content-Type, text/plain
            - AddRequestParameter=name, tony

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
    instances:
      products:
        base-config: default
  timelimiter:
    configs:
      default:
        timeout-duration: 2s
    instances:
      products:
        base-config: default

logging:
  pattern:
   level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
#    reactor.netty.http.client: DEBUG

          #filters:
            #- StripPrefix=2
            #- name: Roadmap # has to be factory prefix
              #args:
                #message: The Cookie Monster is Here
                #cookieValue: CookieMonster
                #cookieName: user

          #predicates:
            #- Path=/products/**
            #- Header= token, \d+
            #- Method= GET,POST
            #- Query= color
            #- Cookie= color, lightBlue
