server:
  port: ${PORT:0}

spring:
  application:
    name: product-msvc
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    username: root
    password: 11037
    url: jdbc:mysql://localhost:3306/product_msvc
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true


logging:
  level:
    org:
      hibernate:
        SQL: debug

eureka:
  instance:
    host-name: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka