server:
  port: 9080

spring:
  application:
    name: product-msvc
  config:
    import: optional:configserver:http://localhost:8888
    
eureka:
  instance:
    host-name: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka