server:
  port: 8082

spring:
  application:
    name: item-msvc
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    host-name: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

